export const KHACHHANG_DANGNHAP_REQUEST = 'KHACHHANG_DANGNHAP_REQUEST';
export const KHACHHANG_DANGNHAP_THANHCONG = 'KHACHHANG_DANGNHAP_THANHCONG';
export const KHACHHANG_DANGNHAP_THATBAI = 'KHACHHANG_DANGNHAP_THATBAI';

export const KHACHHANG_DANGKI_REQUEST = 'KHACHHANG_DANGKI_REQUEST';
export const KHACHHANG_DANGKI_THANHCONG = 'KHACHHANG_DANGKI_THANHCONG';
export const KHACHHANG_DANGKI_THATBAI = 'KHACHHANG_DANGKI_THATBAI';

export const KHACHHANG_DANGXUAT = 'KHACHHANG_DANGXUAT';