export const CUS_GETALLHOTEL_REQUEST = 'CUS_GETALLHOTEL_REQUEST';
export const CUS_GETALLHOTEL_SUCCESS = 'CUS_GETALLHOTEL_SUCCESS';
export const CUS_GETALLHOTEL_FAIL = 'CUS_GETALLHOTEL_FAIL';

export const CUS_GETONEHOTEL_REQUEST = 'CUS_GETONEHOTEL_REQUEST';
export const CUS_GETONEHOTEL_SUCCESS = 'CUS_GETONEHOTEL_SUCCESS';
export const CUS_GETONEHOTEL_FAIL = 'CUS_GETONEHOTEL_FAIL';